### ISSUE TITLE
[Bug]: Test exists for unimplemented `torch.tensor.igamma` frontend instance method

### ISSUE THREAD

**Issue by alexkoziell** [unifyai/ivy#21156]
### Bug Explanation

Test for `torch.tensor.igamma` exists in `ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py` but the actual frontend instance method is not yet implemented in `ivy/functional/frontends/torch/tensor.py`.

PyCharm tests in `ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py` now fail at `top_level_collect` with `E   AttributeError: type object 'Tensor' has no attribute 'igamma'`

---
#### Suspected Cause:

The test introduced in #21031 for the frontend implementation of `torch.igamma` was accidentally written for the `torch.tensor.igamma` instance method.

I think the actual test should have been written in `ivy_tests/test_ivy/test_frontends/test_torch/test_pointwise_ops.py`, rather than `ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py`.

### Steps to Reproduce Bug

Run any of the tests in `ivy_tests/test_ivy/test_frontends/test_torch/test_tensor.py`

### Environment

MacOS with PyCharm

### Ivy Version

1.1.9

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX
